### ISSUE TITLE
cookiecutter master branch installs pyramid==1.10.5

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid-cookiecutter-starter#107]
I caught this when running through the docs. I think that the `master` branch of the cookiecutter should install the `master` branch of pyramid. The only reason I noticed this was when I ran tests and the `imp` error that appears in Pyramid 1.10.5 resurfaced, and I know it was fixed on `master` for the pending 2.0. release.

However I cannot figure out how to do this in setup `requires`, and it appears that link options for VCS has been removed in pip 19.

https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html#dependencies-that-aren-t-in-pypi

I can install Pyramid `master` manually:

```bash
$VENV/bin/pip install -e git+https://github.com/pylons/pyramid.git@master#egg=pyramid 
```

How should we handle this? I could cheat and change `setup.py` to use the 2.0b, but that's a bad pattern to follow when there is no beta or alpha release on PyPI.

**Comment by mmerickel** [comment]
I think it's fine, it's not all intended to work perfectly with pre-release versions. You are expected as a user to sort out certain things when testing a pre-release. When we release pyramid the cookiecutter will work with it.

**Comment by stevepiercy** [comment]
OK. I'll add a note on the master branch to manually install the version of Pyramid you want to test with the GitHub URL, which I always have to look up for correct syntax.
