### ISSUE TITLE
pcreate -s starter app_name is not chameleon

### ISSUE THREAD

**Issue by mikeckennedy** [Pylons/pyramid-cookiecutter-starter#13]
I understand that pcreate is a deprecated operation. However, `pcreate -s starter [app]` is not backwards compatible.

If you type `pcreate -l` you get: 

```
Available scaffolds:
  alchemy:                 Pyramid project using SQLAlchemy, SQLite, URL dispatch, and Jinja2
  pyramid_jinja2_starter:  Pyramid Jinja2 starter project
  starter:                 Pyramid starter project using URL dispatch and Chameleon
  zodb:                    Pyramid project using ZODB, traversal, and Chameleon
```

Yet running `pcreate -s starter [app]` generates a *jinja2* based app even though the listing has been and continues to be chameleon.

**Comment by stevepiercy** [comment]
The summary is wrong for starter on 1.8-branch and master:
https://github.com/Pylons/pyramid/blob/1.8-branch/pyramid/scaffolds/__init__.py#L55

Pyramid 1.7 used Chameleon, and we overlooked this detail for 1.8.

**Comment by mmerickel** [comment]
This belongs in the Pyramid issue tracker as it has nothing to do with this cookiecutter.

**Comment by stevepiercy** [comment]
Fixed in referenced PRs above.
