### ISSUE TITLE
sqlalchemy: stamp should not use `None`

### ISSUE THREAD

**Issue by ctheune** [Pylons/pyramid-cookiecutter-starter#134]
I stumbled over this while adding type stubs to my pyramid project:
https://github.com/sqlalchemy/alembic/issues/1420#issuecomment-1938707864

So this (and a few lines later) should rather use `"base"` instead of `None` as the revision.

https://github.com/Pylons/pyramid-cookiecutter-starter/blob/0baa17979f0c683879e8b8b829e2b5d3b0a0e225/%7B%7Bcookiecutter.repo_name%7D%7D/tests/sqlalchemy_conftest.py#L35

**Comment by mmerickel** [comment]
Awesome, we can make that change. Thanks for the report!
