### ISSUE TITLE
Add "css and js slots" to the template

### ISSUE THREAD

**Issue by mikeckennedy** [Pylons/pyramid-cookiecutter-starter#16]
We have a spot where each individual page can put its content. But sometimes we want to include either a JS file or CSS file for just one page / template.

I think we should have additional, optional sections to allow the page to punch in a CSS below the default css on the top or JS file at the bottom below the default JS.

Thoughts?

**Comment by stevepiercy** [comment]
I think that would be a good unofficial cookiecutter feature (not supported by Pylons) or a Pyramid Community Cookbook recipe, but not part of the official Pylons cookiecutter.

Factors behind my thoughts are:
* Maintenance burden by core developers (code, tests, docs)
* Consistency across the 3 officially supported cookiecutters
* Compatibility with pyramid_debugtoolbar
* The primary purpose of official cookiecutters and scaffolds is to generate a project and install its dependencies. I think that reaching into UI and generating additional website pages, CSS, and JS is beyond the scope of an official Pylons cookiecutter.

**Comment by mikeckennedy** [comment]
Sure, maybe I'll create a custom template integrating some of these ideas.
