### ISSUE TITLE
Can we have a random port?

### ISSUE THREAD

**Issue by mikeckennedy** [Pylons/pyramid-cookiecutter-starter#17]
Currently, every project is set to run on 6543.

This is annoying if we want to run two projects at the same time. This could easily be fixed if we randomly choose a port between 6000-9999 each time we gen the project. I'll do this if you like the idea.

**Comment by stevepiercy** [comment]
It is annoying in that situation, but it's a seldom occurring one that is easily resolved by the developer who edits their `development.ini` file. This suggested change would require numerous tedious changes to the docs including source code files in tutorials.

**Comment by mikeckennedy** [comment]
Fair enough about the cascading changes. I don't want to trigger those!.
