### ISSUE TITLE
Bower or NPM for static resources?

### ISSUE THREAD

**Issue by mikeckennedy** [Pylons/pyramid-cookiecutter-starter#18]
We currently link to CDN files for jquery, respondjs, bootstrap, etc. This is annoying because if you want to work with these projects without internet access you're kinda stuck. Think coffee shop with poor wifi, or on a train/plane, etc.

I propose we use either NPM or Bower to install these into the static folder. This means users can `bower upgrade` or `npm upgrade` as they want but aren't dependent upon network access.

Thoughts? I'll do this if you're keen.

**Comment by stevepiercy** [comment]
I think this is overreaching for an official Pylons cookiecutter for the same reasons I cited in [my comment in #16](https://github.com/Pylons/pyramid-cookiecutter-starter/issues/16#issuecomment-283288834). Additionally I like that the scaffolds and cookiecutters install the bare minimum required to start a project, and let me choose what and how I need for my project beyond that.

How would we deal with users who have never installed or used `npm`, `bower`, or whatever package manager and other dependencies? Would we tell them to just `npm install all-the-things-globally` (which is IMO a horrible thing to do, just as it is in Python).

**Comment by mikeckennedy** [comment]
Hi Steve,

They never need to install, use, or understand npm or bower for this to work. If they don't, the files just live in a subdirectory and are static like everything else.

If they have, know, and want to use these tools, then it's ready to use for updates, management, etc.

**Comment by mmerickel** [comment]
I think I'd be more inclined to just vendor the 3-4 files required to make the projects work offline. You can't just add npm because it doesn't install things into the correct directories so you'd need another procedure on top to copy / link the files into the static folders from `node_modules`. Also I consider bower completely obsolete and not worth talking about.

**Comment by stevepiercy** [comment]
Vendor in sounds good to me. I'd accept a PR for that, then refactor the tutorials.

**Comment by mikeckennedy** [comment]
Sorry guys but can one of you help me with the terminology here: vendor the 3-4 files required 

What does "vendor" mean?

**Comment by blaflamme** [comment]
IMHO any project started with the scaffold would get rid of the assets and template as soon as one start working on it. I agree the template won't render ok if you're not connected to the internet, but I don't think adding those assets are great value, and we'll have to update them as they get new versions. That'd ne more odd to provide old assets than linking them to the internet. Also to install the cookiecutter and project with pip you'll need internet access.

**Comment by mikeckennedy** [comment]
Makes sense to me. I'm happy to no pursue this path. I just wanted to throw out the ideas I had after working with the template. :)

**Comment by stevepiercy** [comment]
> ...we'll have to update them as they get new versions. That'd ne more odd to provide old assets than linking them to the internet.

Good points. I retract my willingness to accept a PR for vendoring in the assets due to the potential increased maintenance burden and limited practicality.

**Comment by mmerickel** [comment]
I think the maintenance argument here is invalid because we're already pinning to specific versions of the resources on the CDNs. For example, bootstrap is pinned to 3.0.3. The difference here is that we have to copy the files into the repo versus updating the number. Neither one is a big deal.

@mikeckennedy By "vendoring" I mean copying the `.js`, `.css`, etc into the scaffold's `static` folder and linking to it there via `request.static_url(...)`.

**Comment by stevepiercy** [comment]
If it's just a link to an external CDN, then we only need to update the link, and not all the static files in the various tutorials and examples. One find/replace is a lot easier to maintain than vendoring in static assets.

**Comment by mmerickel** [comment]
I guess we'll have to disagree on that point. We certainly don't update the web dependencies regularly (bootstrap 3.0.3 is very old) so having things work offline and needing to re-render the tutorials doesn't seem like a huge extra effort over the current pain. I suppose at the very least it might be good to document all the places that need updates when the cookiecutter changes.
