### ISSUE TITLE
Add structure to templates folder

### ISSUE THREAD

**Issue by mikeckennedy** [Pylons/pyramid-cookiecutter-starter#20]
I would like to move `layout.py` / `layout.jinja2` to a folder called `shared` and rename them to `_layout.*` to indicate they are never meant to be the top-level template. Thoughts?

**Comment by stevepiercy** [comment]
I understand why this is important, but this is a highly subjective matter. Some developers toss all templates into `templates`, some use a `shared` or `core`, some organize templates to align across models and views, and still others organize into self-contained Python modules.

**Comment by mikeckennedy** [comment]
Sure, fair enough. :)
