### ISSUE TITLE
The helper message to install after execution is wrong

### ISSUE THREAD

**Issue by mikeckennedy** [Pylons/pyramid-cookiecutter-starter#21]
Currently, we have this:

    env/bin/pip install -e ".[testing]"

But that directory is not there. It needs to be

    env/bin/pip install -e "{{cookiecutter.repo_name}}/.[testing]"

(or \ for windows)

**Comment by stevepiercy** [comment]
Assuming the user follows the preceding three steps, including `cd MyProject`, then `env/bin/pip install -e ".[testing]"` should work.

The forward/backward slash issue for directories pops up from time to time, and we try to accommodate Windows users when in it makes sense. I think in cookiecutter implementations, it would be a nice touch.

It would be onerous to update the official Pyramid docs accordingly, although perhaps an ambitious Windows user could raise the gauntlet there.

**Comment by mikeckennedy** [comment]
Hi Steve,

It doesn't work though. If you CD down one directory, then the command must be:

../env/bin/pip install -e ".[testing]"

notice the .. to go back up to get to the VENV. 

I don't have a strong opinion here. Of all the things I suggested, this is the only one that is a full on bug.

**Comment by mikeckennedy** [comment]
Here are both possibilities, either they don't or do CD into their dir (see that both fail):

![screen shot 2017-03-01 at 6 45 34 am](https://cloud.githubusercontent.com/assets/2035561/23464670/b62c5ba4-fe4a-11e6-8160-cf19ebd27c3e.png)

You could simplify these steps by having them activate the VENV then the relative paths can go away.

**Comment by mmerickel** [comment]
What am I missing here? It seems you are ignoring the first step in the process even in your shell screenshot example where you do not follow the directions exactly. `cd proj` first then create the virtualenv.

**Comment by mikeckennedy** [comment]
I see. The confusion was that I guess I didn't see this as a sequence of events.

Step 1. cd proj
Step 2. make env
Step 3. install

etc.

It seems (because there are no bullets or numbers) to be a set of commands available to me at this moment. 

For example, it seems out of place to immediate run my tests right after project creation before I even start to dev it. 

What do you think? Is this going to be a common misunderstanding or was I just sleepy when I tried it?

**Comment by stevepiercy** [comment]
You're the first! 🥇 

I think if it becomes a common problem, then we could include a line at the top, something like:

```rst
To install and begin work on your project, execute the following commands.
```

**Comment by mikeckennedy** [comment]
Sure, I'll close it for now.
