### ISSUE TITLE
Cookiecutter for mako templates

### ISSUE THREAD

**Issue by petrblahos** [Pylons/pyramid-cookiecutter-starter#23]
Seeing there is a choice of chameleon and jinja2 templates, I am wondering if we 
should be adding an option to choose mako templates?

**Comment by petrblahos** [comment]
Made a pull request: https://github.com/Pylons/pyramid-cookiecutter-starter/pull/24

I am not sure too much choice would not be harmful in the starter template though...

**Comment by stevepiercy** [comment]
Closed in #24
