### ISSUE TITLE
pkg_resources.DistributionNotFound

### ISSUE THREAD

**Issue by eddyekofo94** [Pylons/pyramid-cookiecutter-starter#31]
`pkg_resources.DistributionNotFound: The 'my_project' distribution was not found and is required by the application`

whenever I start my project I keep on getting this error, I can't seem to fix it, I followed all the steps on the README.txt, not sure what's the problem.
I create my virtual environment like this: `virtualenv -p python3 env`

Thank you.

**Comment by stevepiercy** [comment]
The [README.txt](https://github.com/Pylons/pyramid-cookiecutter-starter/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/README.txt#L13) uses `python3 -m venv env`. Try that, and follow the README.txt exactly, then let us know if there is still a problem.

**Comment by eddyekofo94** [comment]
`python3 -m venv env` to `python3 -m venv ./env` adding `./` fixed it on macOS, thank you.
