### ISSUE TITLE
do not create a virtualenv

### ISSUE THREAD

**Issue by mmerickel** [Pylons/pyramid-cookiecutter-starter#4]
I've been thinking about this as I dive into getting things sorted for an official release. There are several issues with having the cookiecutter automatically create a virtualenv that I want on the record before we go forward.

First, the easy one.. the inconsistency that it doesn't work on Python 2.7. Not a big deal but definitely a con.

Second, the real issue to me is that the user no longer has control over which python is used for the scaffold. It's coupled to the python that cookiecutter is installed in, which can be hard to trace. For example, cookiecutter is installable from homebrew (`brew install cookiecutter`). This currently defaults to python2.7 and thus does not create a virtualenv.

On top of that the pre-hook says it will create a virtualenv (even when it won't - this obviously needs to be fixed either way). And, even when it does, the pre-hook doesn't pause to let the user know.. it's just a quick message that scrolls by so I'm not sure what the point of it is. Maybe it should at least ask the user if they want to create a virtualenv?

In general I do not think that having the cookiecutters create virtualenvs helps with the tutorial situation... in my opinion it probably makes them slightly harder to explain due to some of these things that can go wrong.

Finally, there's very few cookiecutters that I've seen that try to do this and so it's not really expected by anyone - and doing things that are unexpected is usually not a good sign.

What do other people think?

@bertjwregeer, @stevepiercy, @cguardia, @blaflamme

**Comment by digitalresistor** [comment]
Where does it create the virtualenv? Because this whole `env` in project dir nonsense is not something I buy into, so I'd be opposed to it from that standpoint.

I want cookiecutter to create the entire directory structure, all the files, templated out, and off I go.

That way I can choose whatever Python version I please for my environment.

**Comment by mmerickel** [comment]
Well I just put a bunch of work into configuring a test suite for the scaffold that runs the pyramid app's tests in its configured virtualenv. As part of that I got the virtualenv working on python 2. The virtualenv is created in a cookiecutter hook. You can see it here:

https://github.com/Pylons/pyramid-cookiecutter-starter/blob/2355a7fcfc738d434cfed76bd9976ea33dffefeb/hooks/post_gen_project.py

I also do not install the virtualenv in my project folder directly (I always use an `env` folder). However, our tutorials have always shown it the way the scaffold is currently doing it, for better or worse.

**Comment by stevepiercy** [comment]
If users install cookiecutter into a virtual environment, it would be nice for cookiecutter not to create a virtual environment inside the virtual environment, and instead use the existing virtual environment. Would that be possible?

Also, minor detail, the pregen script message should use `virtual environment` not `venv`.

**Comment by pauleveritt** [comment]
I was the one that lobbied for making a virtual environment as part of the construction. cookiecutter is our way of helping newcomers correctly construct a working project. We document that you should do virtual environments. It makes sense to try.

I understand if there are mechanical reasons that cause it to be retracted.

One final note: thank goodness it does the right thing and stores the virtual environment in the project. :)
—Paul

**Comment by pauleveritt** [comment]
@mmerickel You bring up the Homebrew cookiecutter and say it's impossible to use it and result in a virtual environment. If so, our docs say you REALLY should use virtual environments. That means the Homebrew cookiecutter is a red herring, as we should discourage using it.

On the other points, perhaps most would be solved by make it an optional flag. If you opt into it, you know to expect its results.

**Comment by stevepiercy** [comment]
Homebrew is an alternative method to install cookiecutter itself, not the Pyramid cookiecutters. cookiecutter's [recommended installation method](https://cookiecutter.readthedocs.io/en/latest/installation.html) is via `[sudo] pip install cookiecutter`. Some users will install cookiecutter in the system Python, whether it's by Homebrew, pip, or easy_install.

Some users may install cookiecutter in a virtual environment (like me), and not want to "pimp their virtual environment" (Yo, Dawg, I put a virtual environment *inside* your virtual environment!).

I would like to preserve the creation of a virtual environment by the Pyramid cookiecutters, but as an option, if possible. Let the user choose whether to create a virtual environment or use an existing one via a user input option for the cookiecutter. I would prefer the default for this option to be not to create a virtual environment.

If I had to choose only one method to be implemented for the Pyramid cookiecutters, I'd say drop the creation of a virtual environment. The Pyramid docs are adamant about using virtual environments already, so I think only minor adjustments there would be necessary.

**Comment by blaflamme** [comment]
> If I had to choose only one method to be implemented for the Pyramid cookiecutters, I'd say drop the creation of a virtual environment.

I'm with this. I think as a developer you should know about venvs and as a scaffold it should not be too magical about it. If it can be an option it'll be great, if not don't make it a blind default. Newbs won't understand what's going on, and others would just drop it and recreate the way they want.

**Comment by mmerickel** [comment]
@pauleveritt 

> You bring up the Homebrew cookiecutter and say it's impossible to use it and result in a virtual environment. If so, our docs say you REALLY should use virtual environments. That means the Homebrew cookiecutter is a red herring, as we should discourage using it.

It's not that it won't work (I added support last night so it'll auto-create virtualenvs if virtualenv package is available). It's just that it will be a virtualenv created in Python 2.7 instead of super cool Python 3.x.

I can add a configuration option for creating the virtualenv (y/n). I'm a little bummed that people would accidentally end up with a virtualenv using Python 2 unknowingly but I can't think of much of a way around it right now that fits into cookiecutter.

I could try to add a function to jinja2 which can pre-populate a `cookiecutter.json` setting `virtualenv_python` based on what pythons it finds on the system. That feels a bit silly though.

Another option would be to shell out to the system and just try to run "python3 -m venv" instead of using the `venv.create` api. This would let us escape whatever python we are running inside cookiecutter and fallback to the system path. If the command fails we can just have a message begging the user to setup a virtualenv.

I sort of feel like this is jumping through hoops to solve something that isn't actually that hard for a user to solve themselves. This code also doesn't support windows very well yet considering all the commands are using "bin" instead of "Scripts" so it's just going to get more complex.

**Comment by mmerickel** [comment]
Okay, here are the best 2 options I've settled on:

1) Remove virtualenv creation from the cookiecutter. We then keep the docs basically where they are now... the user installs the cookiecutter and then they manually setup their virtualenv.

2) Add a `create_virtualenv` option which is `y/n`. The auto-creation could just shell out to `py -3 -m venv .` on windows and `python3 -m venv .` on other systems. If it fails then it fails and you'll need to create your own virtualenv.

The bummer about option 2 is that it it can leave the user in 2 different states which has to be dealt with gracefully.

Can ya'll shoot me some opinions?

**Comment by stevepiercy** [comment]
Per IRC, I've reached the same conclusion. I prefer option 1 over 2.

Also to capture the process for updating docs for option 1:

# Generate a project via Pyramid cookiecutters (Option 1)

```shell
# 1. Make a directory to contain cookiecutter and change directory into it.
mkdir mycc && cd mycc
# 2. Create a virtual environment...
python3 -m venv env
# 3. ...where we upgrade packaging tools...
env/bin/pip install --upgrade pip setuptools wheel
# 4. ...and into which we install cookiecutter.
env/bin/pip install cookiecutter
# 5. Create a Pyramid project via cookiecutter.
env/bin/cookiecutter gh:Pylons/pyramid-cookiecutter-starter
<follow prompts>
# 6. Change directory into our newly created project.
cd <project_name>
# 7. Create a second virtual environment...
python3 -m venv env
# 8. ...where we upgrade packaging tools...
env/bin/pip install --upgrade pip setuptools wheel
# 9. ...and into which we install our project and its testing requirements.
env/bin/pip install -e .[testing]
# 10. Run tests on our project.
env/bin/py.test
```

I'd like feedback on the draft docs revisions, too.

**Comment by pauleveritt** [comment]
I understand when I’m outvoted, so no virtualenv for our cookiecutters. :)

—Paul

**Comment by mmerickel** [comment]
> I understand when I’m outvoted, so no virtualenv for our cookiecutters. :)

Okay well it's bittersweet because I definitely think auto-creating the virtualenv is slick when it works. I just want a workflow that has the highest chance of working the same way for everyone. Hopefully it'll be easier to document that way as well.

I'll work on this during the holiday and hopefully we can get the docs updated and a pyramid alpha out the door in the next couple weeks!
