### ISSUE TITLE
Update readme with correct instructions

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid-cookiecutter-starter#6]
See also https://github.com/Pylons/pyramid-cookiecutter-starter/issues/4#issuecomment-262450839

**Comment by mmerickel** [comment]
This should be done but feel free to tweak it.

**Comment by stevepiercy** [comment]
@mmerickel I noticed you skipped over the installation of cookiecutter. Why is that? Is it something best left to the authors of cookiecutter and for us not taking on more maintenance burden?

**Comment by stevepiercy** [comment]
Closed by #10
