### ISSUE TITLE
gunicorn needs host + port instead of listen

### ISSUE THREAD

**Issue by hyperknot** [Pylons/pyramid-cookiecutter-starter#68]
In the INI files, gunicorn can only parse port if it's specified in two lines, as `host` + `port`, and not in a single line as `listen`.

**Comment by mmerickel** [comment]
The data in the server section is custom to each runner. There is not a goal to make that section a subset of settings that works across server runners.

**Comment by hyperknot** [comment]
It might be custom, but `host` + `port` works with both of them, while `listen` only works for waitress.

**Comment by mmerickel** [comment]
My understanding is that listen is more featureful and recommended in waitress.

I'd rather not use the less-preferred version in waitress just so you don't have to think about the settings when you switch to gunicorn. When modifying which server you use you *should* look at the settings for that server and set them appropriately.
