### ISSUE TITLE
DeprecationWarning: Use of .. or absolute path in a resource path is not allowed and will raise exceptions in a future release.

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid-cookiecutter-starter#75]
After creating a new project with cookiecutter, running the tests results in the error:

`DeprecationWarning: Use of .. or absolute path in a resource path is not allowed and will raise exceptions in a future release.`

This can be fixed by using the package name instead of `..` in the views templates. PR coming soon.

**Comment by stevepiercy** [comment]
Fixed by #76

**Comment by smsearcy** [comment]
This fix was never merged into the `latest` branch, so following the default instructions in the README still results in this warning nearly a year later.  Can this be corrected?

**Comment by stevepiercy** [comment]
Please see https://github.com/Pylons/pyramid-cookiecutter-starter#versions for a description of how versions are managed.

To use the master branch, see https://github.com/Pylons/pyramid-cookiecutter-starter/tree/master#usage

**Comment by smsearcy** [comment]
Thank you, I had seen that but gotten confused about the branches, it's clear now.
