### ISSUE TITLE
.coverage includes `omit` that no longer exists

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid-cookiecutter-starter#82]
@mmerickel should this line have been removed with the move of tests outside of the source directory?

https://github.com/Pylons/pyramid-cookiecutter-starter/blob/df364cd2dacaf42f48187a87d5098cc730e45c73/%7B%7Bcookiecutter.repo_name%7D%7D/.coveragerc#L3

**Comment by mmerickel** [comment]
Yeah probably can be removed or changed to just `tests/` but I’d remove it.

**Comment by stevepiercy** [comment]
OK, I'll jump on this one, and make another pass. Should be quick.

**Comment by stevepiercy** [comment]
Closed by #83
